{
    "name": "bablu-footwear",
    "region": "singapore",
    "env": {
        "PYTHON_VERSION": "3.12.0"
    },
    "buildCommand": "pip install -r requirements.txt && pip install pymongo",
    "startCommand": "gunicorn --log-level debug app:app",
    "rootDir": ".",
    "envVars": {
        "FLASK_APP": "app.py",
        "FLASK_ENV": "production",
        "PYTHONPATH": "."
    }
}